### ISSUE TITLE
Opening a URL wipes Firefox settings

### ISSUE THREAD

**Issue by iONinja** [rauschma/openurl#7]
Hi there,

I'm using Ubuntu 14.04 with Firefox 54.0 (64-bit).
I used `openurl` to open a URL in Firefox, and then closed the browser.

Incidentally, I got these errors in the terminal (after closing the browser window):
```
Error: 
(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:5945): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    at Socket.<anonymous> (/home/luke/io1/node_modules/openurl/openurl.js:35:25)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
But that's not the main issue. When I opened Firefox, it forgot all my settings, theme, etc. Although, it remembered by account and history.

So what's going on here?

**Comment by rauschma** [comment]
I don’t know! openurl does very little, so it’s almost certainly a Firefox bug.

**Comment by iONinja** [comment]
@rauschma

Yeah, it also happens with `opn` and when using `exec` from `child_process`. The same issue seems to occur with Google Chrome, as well.
