### ISSUE TITLE
Throwing Error: Error: ATTENTION: default value of option force_s3tc_enable overridden by environment.

### ISSUE THREAD

**Issue by adam-s** [rauschma/openurl#9]
This module ships with [Apollo 2 Universal Starter Kit ](https://github.com/sysgears/apollo-universal-starter-kit). On running the script an error is thrown which I don't understand.

```
spin error Error: ATTENTION: default value of option force_s3tc_enable overridden by environment.

    at Socket.<anonymous> (/home/adam/PhpstormProjects/joboty/node_modules/openurl/openurl.js:35:25)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by adam-s** [comment]
This seems to deal specifically with Chrome being set as my default browser in Ubuntu and openurl console logs the error being thrown on my local development machine instead of just opening the webpage without logging. This is not an openurl issue.
